# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!

platform :ios, '9.0'

def target_pods
  pod 'google-cast-sdk'
end

target 'FriendlyPlayer' do
  target_pods
end
